<?php
require_once '../config/db.php';

if (!isset($_SESSION['user']) || $_SESSION['user']['jabatan'] != 'Administrator') {
    header('Location: ../index.php');
    exit;
}

require_once '../config/menu_config.php';

$action = $_GET['action'] ?? 'view';
$message = '';
$error = '';

// Simpan menu ke file konfigurasi
if ($_SERVER['REQUEST_METHOD'] == 'POST' && $action == 'save') {
    $menus = $_POST['menus'] ?? [];
    
    // Validasi dan proses data menu
    $processedMenus = [];
    foreach ($menus as $index => $menu) {
        if (!empty($menu['title']) && !empty($menu['url'])) {
            $processedMenus[] = [
                'id' => $menu['id'] ?? 'menu_' . uniqid(),
                'title' => htmlspecialchars($menu['title']),
                'icon' => htmlspecialchars($menu['icon']),
                'url' => htmlspecialchars($menu['url']),
                'roles' => isset($menu['roles']) ? explode(',', $menu['roles']) : ['all'],
                'position' => $menu['position'] ?? 'main',
                'order' => (int)($menu['order'] ?? $index * 10),
                'parent_id' => !empty($menu['parent_id']) ? $menu['parent_id'] : null
            ];
        }
    }
    
    // Generate PHP code untuk menyimpan menu
    $phpCode = "<?php\n// Konfigurasi Menu - Generated by Menu Manager\n";
    $phpCode .= "return " . var_export($processedMenus, true) . ";\n";
    
    // Simpan ke file
    $filename = '../config/menu_generated.php';
    if (file_put_contents($filename, $phpCode)) {
        $message = 'Menu berhasil disimpan!';
    } else {
        $error = 'Gagal menyimpan menu. Pastikan folder config memiliki izin tulis.';
    }
}

// Ambil menu yang ada
$currentMenus = MenuConfig::getAllMenus();
$allRoles = MenuConfig::getAllRoles();
?>

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu Manager - Admin</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/feather-icons"></script>
</head>
<body class="bg-gray-50 min-h-screen">
    <?php include '../components/header.php'; ?>
    <?php include '../components/navigation.php'; ?>
    
    <main class="container mx-auto px-4 py-8">
        <div class="bg-white rounded-2xl shadow-lg p-6 mb-8">
            <h2 class="text-2xl font-bold text-gray-800 mb-2">Menu Manager</h2>
            <p class="text-gray-600">Kelola menu navigasi website dengan mudah</p>
        </div>
        
        <?php if ($message): ?>
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-6">
                <?= $message ?>
            </div>
        <?php endif; ?>
        
        <?php if ($error): ?>
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
                <?= $error ?>
            </div>
        <?php endif; ?>
        
        <div class="bg-white rounded-2xl shadow-lg p-6">
            <form method="POST" action="?action=save">
                <div class="overflow-x-auto">
                    <table class="w-full table-auto">
                        <thead class="bg-gray-50">
                            <tr>
                                <th class="px-4 py-3 text-left">Order</th>
                                <th class="px-4 py-3 text-left">Title</th>
                                <th class="px-4 py-3 text-left">Icon</th>
                                <th class="px-4 py-3 text-left">URL</th>
                                <th class="px-4 py-3 text-left">Roles</th>
                                <th class="px-4 py-3 text-left">Position</th>
                                <th class="px-4 py-3 text-left">Parent ID</th>
                                <th class="px-4 py-3 text-left">Actions</th>
                            </tr>
                        </thead>
                        <tbody id="menu-container">
                            <?php foreach ($currentMenus as $index => $menu): ?>
                            <tr class="border-t">
                                <td class="px-4 py-3">
                                    <input type="number" name="menus[<?= $index ?>][order]" 
                                           value="<?= $menu['order'] ?? $index * 10 ?>"
                                           class="w-20 px-2 py-1 border rounded">
                                </td>
                                <td class="px-4 py-3">
                                    <input type="text" name="menus[<?= $index ?>][title]" 
                                           value="<?= htmlspecialchars($menu['title']) ?>"
                                           class="px-2 py-1 border rounded w-40" required>
                                </td>
                                <td class="px-4 py-3">
                                    <input type="text" name="menus[<?= $index ?>][icon]" 
                                           value="<?= $menu['icon'] ?? '' ?>"
                                           class="px-2 py-1 border rounded w-32">
                                </td>
                                <td class="px-4 py-3">
                                    <input type="text" name="menus[<?= $index ?>][url]" 
                                           value="<?= htmlspecialchars($menu['url']) ?>"
                                           class="px-2 py-1 border rounded w-48" required>
                                </td>
                                <td class="px-4 py-3">
                                    <input type="text" name="menus[<?= $index ?>][roles]" 
                                           value="<?= is_array($menu['roles']) ? implode(',', $menu['roles']) : $menu['roles'] ?>"
                                           class="px-2 py-1 border rounded w-48"
                                           placeholder="all,Administrator,Staf">
                                </td>
                                <td class="px-4 py-3">
                                    <select name="menus[<?= $index ?>][position]" class="px-2 py-1 border rounded">
                                        <option value="main" <?= ($menu['position'] ?? 'main') == 'main' ? 'selected' : '' ?>>Main</option>
                                        <option value="right" <?= ($menu['position'] ?? '') == 'right' ? 'selected' : '' ?>>Right</option>
                                        <option value="mobile-only" <?= ($menu['position'] ?? '') == 'mobile-only' ? 'selected' : '' ?>>Mobile Only</option>
                                    </select>
                                </td>
                                <td class="px-4 py-3">
                                    <input type="text" name="menus[<?= $index ?>][parent_id]" 
                                           value="<?= $menu['parent_id'] ?? '' ?>"
                                           class="px-2 py-1 border rounded w-32">
                                </td>
                                <td class="px-4 py-3">
                                    <button type="button" onclick="removeRow(this)" 
                                            class="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded">
                                        Hapus
                                    </button>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                
                <div class="mt-6 flex justify-between">
                    <button type="button" onclick="addRow()" 
                            class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">
                        + Tambah Menu
                    </button>
                    
                    <button type="submit" 
                            class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">
                        Simpan Perubahan
                    </button>
                </div>
            </form>
        </div>
        
        <div class="mt-8 bg-white rounded-2xl shadow-lg p-6">
            <h3 class="text-lg font-bold text-gray-800 mb-4">Informasi Roles/Jabatan</h3>
            <div class="grid grid-cols-2 md:grid-cols-5 gap-4">
                <?php foreach ($allRoles as $role): ?>
                    <div class="bg-gray-100 p-3 rounded-lg">
                        <p class="font-semibold text-gray-700"><?= $role ?></p>
                        <p class="text-sm text-gray-500">Gunakan koma untuk multiple roles</p>
                    </div>
                <?php endforeach; ?>
                <div class="bg-green-100 p-3 rounded-lg">
                    <p class="font-semibold text-green-700">all</p>
                    <p class="text-sm text-green-600">Semua user bisa akses</p>
                </div>
            </div>
        </div>
    </main>
    
    <script>
        feather.replace();
        
        let rowCount = <?= count($currentMenus) ?>;
        
        function addRow() {
            const container = document.getElementById('menu-container');
            const newRow = document.createElement('tr');
            newRow.className = 'border-t';
            newRow.innerHTML = `
                <td class="px-4 py-3">
                    <input type="number" name="menus[${rowCount}][order]" 
                           value="${rowCount * 10}"
                           class="w-20 px-2 py-1 border rounded">
                </td>
                <td class="px-4 py-3">
                    <input type="text" name="menus[${rowCount}][title]" 
                           class="px-2 py-1 border rounded w-40" required>
                </td>
                <td class="px-4 py-3">
                    <input type="text" name="menus[${rowCount}][icon]" 
                           class="px-2 py-1 border rounded w-32">
                </td>
                <td class="px-4 py-3">
                    <input type="text" name="menus[${rowCount}][url]" 
                           class="px-2 py-1 border rounded w-48" required>
                </td>
                <td class="px-4 py-3">
                    <input type="text" name="menus[${rowCount}][roles]" 
                           class="px-2 py-1 border rounded w-48"
                           value="all" placeholder="all,Administrator,Staf">
                </td>
                <td class="px-4 py-3">
                    <select name="menus[${rowCount}][position]" class="px-2 py-1 border rounded">
                        <option value="main">Main</option>
                        <option value="right">Right</option>
                        <option value="mobile-only">Mobile Only</option>
                    </select>
                </td>
                <td class="px-4 py-3">
                    <input type="text" name="menus[${rowCount}][parent_id]" 
                           class="px-2 py-1 border rounded w-32">
                </td>
                <td class="px-4 py-3">
                    <button type="button" onclick="removeRow(this)" 
                            class="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded">
                        Hapus
                    </button>
                </td>
            `;
            container.appendChild(newRow);
            rowCount++;
        }
        
        function removeRow(button) {
            const row = button.closest('tr');
            row.remove();
        }
    </script>
</body>
</html>